# constants

### GENERAL ###
NAME_GAME = "Cometa"
GAME_OVER_SCREEN = "Game Over Screen"
FPS = 60

### DB CONFIGURATION ###
IP_DB_SERVER = "localhost"
PORT_DB_SERVER = 3306
USER_DB_SERVER = "root"
PASSWORD_DB_SERVER = "123456"
DB_SCHEMA = "cometa"


### QUERIES CONFIGURATION ###